apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "redis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "redis.chart" . }}
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  hostPath:
    path: {{ .Values.persistence.hostPath }}
